POST http://localhost:3000/biconomy/send
Content-Type: application/json

{
  "to": "0x329Fb58Fe6706FB6945715287fbc39cFeC36654A",
  "value": 100
}

### Biconomy deploy endpoint

POST http://localhost:3000/biconomy/deploy HTTP/1.1
Content-Type: application/json

{
  "defaultAdmin": "0xEC12D8BE763a910C05FaE3b39E7575064d3EbcD0",
  "minter": "0xEC12D8BE763a910C05FaE3b39E7575064d3EbcD0"
}

### Mint Tokens Endpoint

POST http://localhost:3000/biconomy/mint
Content-Type: application/json

{
  "contractAddress": "0x3e243D84Ccd9ACA6a34F1C716caC69589D9E69E7",
  "to": "0xEC12D8BE763a910C05FaE3b39E7575064d3EbcD0",
  "amount": "1000"
}

### Burn Tokens Endpoint

POST http://localhost:3000/biconomy/burn
Content-Type: application/json

{
  "contractAddress": "0x3e243D84Ccd9ACA6a34F1C716caC69589D9E69E7",
  "amount": "500"
}

### Transfer Tokens Endpoint

POST http://localhost:3000/biconomy/transfer
Content-Type: application/json

{
  "contractAddress": "0x3e243D84Ccd9ACA6a34F1C716caC69589D9E69E7",
  "recipient": "0x513001e9a21b1b9f5a36779195c4cb5175b7f2Fa",
  "amount": "200"
}

